esprit_Acceuilpage:
    path:     /back
    defaults: { _controller: EspritForAllBackEndBundle:BackEndAcceuil:Back }
AfficheClubs:
    path:     /listclub
    defaults: { _controller: EspritForAllBackEndBundle:Club:ListClub }
UpdateClub:
    path:     /updateclub/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Club:UpdateClub }
AjoutClub:
    path:     /ajoutclub
    defaults: { _controller: EspritForAllBackEndBundle:Club:AjoutClub }
DeleteClub:
    path:     /deleteclub/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Club:DeleteClub }
AfficheEvenement:
    path:     /listEvenement
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:ListEvenement }
AjoutEvenement:
    path:     /ajoutEvent
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:AjoutEvenement }
UpdateEvenement:
    path:     /updateEvenement/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:UpdateEvenement }
DeleteEvenement:
    path:     /deleteEvenementb/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:DeleteEvenement }
_graphePie:
    path:     /pie
    defaults: { _controller: EspritForAllBackEndBundle:Graphe:chartPie}
AfficheDocs:
    path:     /listdoc
    defaults: { _controller: EspritForAllBackEndBundle:Doc:ListDoc }
DeleteDocs:
    path:     /deletdoc/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Doc:Delete }
mailDocs:
    path:     /mail/doc
    defaults: { _controller: EspritForAllBackEndBundle:Doc:SendMail }
Gestion_Menu:
    path:     /restaurent_management
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:index }
edit_menu_item:
    path:     /ajax_request_menu_edit
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:EditMenu }
check_order:
    path:     /ajax_request_check_order
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:CheckOrder }
delete_menu_item:
    path:     /ajax_request_menu_delete
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:DeleteMenu }
add_menu_item:
    path:     /ajax_request_menu_add
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:AddMenu }
update_localstorage:
    path:     /ajax_request_update_local_storage
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:UpdateLS }
restaurent_orders:
    path:     /restaurent_management/orders
    defaults: { _controller: EspritForAllBackEndBundle:RestaurentManagement:Orders }
