esprit_Acceuilpage:
    path:     /back
    defaults: { _controller: EspritForAllBackEndBundle:BackEndAcceuil:Back }
AfficheClubs:
    path:     /listclub
    defaults: { _controller: EspritForAllBackEndBundle:Club:ListClub }
UpdateClub:
    path:     /updateclub/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Club:UpdateClub }
AjoutClub:
    path:     /ajoutclub
    defaults: { _controller: EspritForAllBackEndBundle:Club:AjoutClub }
DeleteClub:
    path:     /deleteclub/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Club:DeleteClub }
AfficheEvenement:
    path:     /listEvenement
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:ListEvenement }
AjoutEvenement:
    path:     /ajoutEvent
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:AjoutEvenement }
UpdateEvenement:
    path:     /updateEvenement/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:UpdateEvenement }
DeleteEvenement:
    path:     /deleteEvenement/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Evenement:DeleteEvenement }
_graphePie:
    path:     /pie
    defaults: { _controller: EspritForAllBackEndBundle:Graphe:chartPie}
AfficheDocs:
    path:     /listdoc
    defaults: { _controller: EspritForAllBackEndBundle:Doc:ListDoc }
DeleteDocs:
    path:     /deletdoc/{id}
    defaults: { _controller: EspritForAllBackEndBundle:Doc:Delete }
mailDocs:
    path:     /mail/doc
    defaults: { _controller: EspritForAllBackEndBundle:Doc:SendMail }
