api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api


front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

esprit_for_all_back_end:
    resource: "@EspritForAllBackEndBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check

fos_user_api_login:
    defaults: { _controller: FOSUserBundle:Security:login }
    path: /api/login
app:
    resource: '@AppBundle/Controller/'
    type: annotation
annonce:
    resource: '@AnnonceBundle/Resources/config/routing.yml'
    prefix:   /annonce