# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    brochures_directory: '%kernel.root_dir%/public/uploads/brochures'
services:
 fos_user.doctrine_registry:
    alias: doctrine
 redirect.after.login:
    class: FrontEndBundle\Controller\Redirection\AfterLoginRedirection
    arguments: ["@router"]

 redirect.after.logout:
    class: EspritForAll\BackEndBundle\Redirection\AfterLogoutRedirection
    arguments: ["@router", "@security.authorization_checker"]

