login_root:
    path:     /login
    defaults: { _controller: FrontEndBundle:Login:index }



front_end_homepage:
    path:     /home
    defaults: { _controller: FrontEndBundle:Default:index }



front_end_resto_home:
    path:     /restaurent
    defaults: { _controller: FrontEndBundle:Restaurent:index }

resto_single_product:
    path:     /restaurent/single_product
    defaults: { _controller: FrontEndBundle:RestaurentSingleProduct:index }

resto_shop_cart:
    path:     /restaurent/shop_cart
    defaults: { _controller: FrontEndBundle:RestaurentShopCart:index }

resto_menu_categories:
    path:     /restaurent/menu
    defaults: { _controller: FrontEndBundle:RestaurentMenu:cotegories }

resto_menu_sub_categories:
    path:     /restaurent/menu/sub_menu
    defaults: { _controller: FrontEndBundle:RestaurentMenu:sub_categories }




front_end_club:
    path:     /club
    defaults: { _controller: FrontEndBundle:Club:index }

front_end_covoiturage:
    path:     /covoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:index }

front_end_cherchercovoiturage:
    path:     /chercherCovoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:chercher }

front_end_verscovoiturage:
    path:     /ajoutCovoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:vers }

front_end_versModifiercovoiturage:
    path:     /modifierCovoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:versm}

front_end_ajoutcovoiturage:
    path:     /aaCovoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:ajout}

front_end_ajoutercovoiturage:
    path:     /listerCovoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:lister}

deleteCovoiturage:
     path:     /deleteCov/{id}
     defaults: { _controller: FrontEndBundle:Covoiturage:delete }

front_end_revision:
    path:     /revision
    defaults: { _controller: FrontEndBundle:Revision:index }

front_end_decremCovoiturage:
    path:     /decrem/{id}
    defaults: { _controller: FrontEndBundle:Covoiturage:decrem }

front_end_decremCovoiturage2:
    path:     /decrem2/{id}
    defaults: { _controller: FrontEndBundle:Covoiturage:decrem2 }

front_end_learnCovoiturage:
    path:     /learn/{id}
    defaults: { _controller: FrontEndBundle:Covoiturage:learn }

front_end_profil:
    path:     /profil
    defaults: { _controller: FrontEndBundle:Profil:index }

