


front_end_homepage:
    path:     /home
    defaults: { _controller: FrontEndBundle:Default:index }



front_end_resto_home:
    path:     /restaurent
    defaults: { _controller: FrontEndBundle:Restaurent:index }

resto_single_product:
    path:     /restaurent/single_product/{id}
    defaults: { _controller: FrontEndBundle:RestaurentSingleProduct:GetMeal }

resto_single_product1:
    path:     /restaurent/single_product
    defaults: { _controller: FrontEndBundle:RestaurentSingleProduct:index }

resto_shop_cart:
    path:     /restaurent/shop_cart
    defaults: { _controller: FrontEndBundle:RestaurentShopCart:ShowUserCard }

resto_menu_categories:
    path:     /restaurent/menu
    defaults: { _controller: FrontEndBundle:RestaurentMenu:cotegories }

resto_menu_sub_categories:
    path:     /restaurent/menu/sub_menu/{type}
    defaults: { _controller: FrontEndBundle:RestaurentMenu:ClickOnSubCategory }

resto_add_to_card:
    path:       /restaurent/{id_menu}/{quantite}
    defaults: { _controller: FrontEndBundle:RestaurentMenu:InsertLigneCommande }

front_end_club:
    path:     /club
    defaults: { _controller: FrontEndBundle:Club:index }

front_end_covoiturage:
    path:     /covoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:index }
AficheRevision:
    path:     /revision
    defaults: { _controller: FrontEndBundle:Revision:ListRev }
AjoutRevision:
    path:     /AjoutRev
    defaults: { _controller: FrontEndBundle:Revision:Ajout }
DeleteRevision:
    path:     /DeleteRev/{id}
    defaults: { _controller: FrontEndBundle:Revision:Delete }
GrpRev:
    path:     /affgrp/{id}
    defaults: { _controller: FrontEndBundle:Revision:redirection }
upRev:
    path:     /upgrp/{id}
    defaults: { _controller: FrontEndBundle:Revision:update }
frontdoc:
    path:     /doc
    defaults: { _controller: FrontEndBundle:DocAdmin:index }
ajout1doc:
    path:     /doc1
    defaults: { _controller: FrontEndBundle:DocAdmin:Ajout1 }
rechercherev:
    path:     /rech
    defaults: { _controller: FrontEndBundle:Revision:search }
GrpRevv:
    path:     /affgrp2
    defaults: { _controller: FrontEndBundle:Revision:redirection2 }
pdf:
    path:     /pdf
    defaults: { _controller: FrontEndBundle:Revision:pdf }
pdf2:
    path:     /pdf2
    defaults: { _controller: FrontEndBundle:Revision:pdf2 }






